apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-flows
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: flowmonitor
      defaultBucket: flows
    secureJsonData:
      token: flowmonitor-secret-token
    isDefault: true
    editable: true
